/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as CartRouteImport } from './routes/cart'
import { Route as CategoriesRouteImport } from './routes/categories'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as WalletRouteImport } from './routes/wallet'
import { Route as AuthenticatedRiderRouteImport } from './routes/_authenticated/rider'
import { Route as AuthenticatedVendorRouteImport } from './routes/_authenticated/vendor'
import { Route as OrdersIndexRouteImport } from './routes/orders.index'
import { Route as OrdersIdRouteImport } from './routes/orders.$id'
import { Route as StallsRouteImport } from './routes/stalls.'
import { Route as SupportIndexRouteImport } from './routes/support.index'
import { Route as SupportIdRouteImport } from './routes/support.$id'
import { Route as ApiPublicCashfreeCallbackRouteImport } from './routes/api/public/cashfree/callback'
import { Route as ApiPublicPayuCallbackRouteImport } from './routes/api/public/payu/callback'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriesRoute = CategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const WalletRoute = WalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRiderRoute = AuthenticatedRiderRouteImport.update({
  id: '/rider',
  path: '/rider',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedVendorRoute = AuthenticatedVendorRouteImport.update({
  id: '/vendor',
  path: '/vendor',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const OrdersIndexRoute = OrdersIndexRouteImport.update({
  id: '/orders/',
  path: '/orders/',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersIdRoute = OrdersIdRouteImport.update({
  id: '/orders/$id',
  path: '/orders/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const StallsRoute = StallsRouteImport.update({
  id: '/stalls/',
  path: '/stalls/',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportIndexRoute = SupportIndexRouteImport.update({
  id: '/support/',
  path: '/support/',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportIdRoute = SupportIdRouteImport.update({
  id: '/support/$id',
  path: '/support/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCashfreeCallbackRoute =
  ApiPublicCashfreeCallbackRouteImport.update({
    id: '/api/public/cashfree/callback',
    path: '/api/public/cashfree/callback',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicPayuCallbackRoute = ApiPublicPayuCallbackRouteImport.update({
  id: '/api/public/payu/callback',
  path: '/api/public/payu/callback',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/cart': typeof CartRoute
  '/categories': typeof CategoriesRoute
  '/notifications': typeof NotificationsRoute
  '/profile': typeof ProfileRoute
  '/terms': typeof TermsRoute
  '/wallet': typeof WalletRoute
  '/stalls/': typeof StallsRoute
  '/rider': typeof AuthenticatedRiderRoute
  '/vendor': typeof AuthenticatedVendorRoute
  '/orders/$id': typeof OrdersIdRoute
  '/support/$id': typeof SupportIdRoute
  '/orders/': typeof OrdersIndexRoute
  '/support/': typeof SupportIndexRoute
  '/api/public/cashfree/callback': typeof ApiPublicCashfreeCallbackRoute
  '/api/public/payu/callback': typeof ApiPublicPayuCallbackRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/cart': typeof CartRoute
  '/categories': typeof CategoriesRoute
  '/notifications': typeof NotificationsRoute
  '/profile': typeof ProfileRoute
  '/terms': typeof TermsRoute
  '/wallet': typeof WalletRoute
  '/stalls': typeof StallsRoute
  '/rider': typeof AuthenticatedRiderRoute
  '/vendor': typeof AuthenticatedVendorRoute
  '/orders/$id': typeof OrdersIdRoute
  '/support/$id': typeof SupportIdRoute
  '/orders': typeof OrdersIndexRoute
  '/support': typeof SupportIndexRoute
  '/api/public/cashfree/callback': typeof ApiPublicCashfreeCallbackRoute
  '/api/public/payu/callback': typeof ApiPublicPayuCallbackRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/cart': typeof CartRoute
  '/categories': typeof CategoriesRoute
  '/notifications': typeof NotificationsRoute
  '/profile': typeof ProfileRoute
  '/terms': typeof TermsRoute
  '/wallet': typeof WalletRoute
  '/stalls/': typeof StallsRoute
  '/_authenticated/rider': typeof AuthenticatedRiderRoute
  '/_authenticated/vendor': typeof AuthenticatedVendorRoute
  '/orders/$id': typeof OrdersIdRoute
  '/support/$id': typeof SupportIdRoute
  '/orders/': typeof OrdersIndexRoute
  '/support/': typeof SupportIndexRoute
  '/api/public/cashfree/callback': typeof ApiPublicCashfreeCallbackRoute
  '/api/public/payu/callback': typeof ApiPublicPayuCallbackRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/cart'
    | '/categories'
    | '/notifications'
    | '/profile'
    | '/terms'
    | '/wallet'
    | '/stalls/'
    | '/rider'
    | '/vendor'
    | '/orders/$id'
    | '/support/$id'
    | '/orders/'
    | '/support/'
    | '/api/public/cashfree/callback'
    | '/api/public/payu/callback'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/auth'
    | '/cart'
    | '/categories'
    | '/notifications'
    | '/profile'
    | '/terms'
    | '/wallet'
    | '/stalls'
    | '/rider'
    | '/vendor'
    | '/orders/$id'
    | '/support/$id'
    | '/orders'
    | '/support'
    | '/api/public/cashfree/callback'
    | '/api/public/payu/callback'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/admin'
    | '/auth'
    | '/cart'
    | '/categories'
    | '/notifications'
    | '/profile'
    | '/terms'
    | '/wallet'
    | '/stalls/'
    | '/_authenticated/rider'
    | '/_authenticated/vendor'
    | '/orders/$id'
    | '/support/$id'
    | '/orders/'
    | '/support/'
    | '/api/public/cashfree/callback'
    | '/api/public/payu/callback'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AdminRoute: typeof AdminRoute
  AuthRoute: typeof AuthRoute
  CartRoute: typeof CartRoute
  CategoriesRoute: typeof CategoriesRoute
  NotificationsRoute: typeof NotificationsRoute
  ProfileRoute: typeof ProfileRoute
  TermsRoute: typeof TermsRoute
  WalletRoute: typeof WalletRoute
  StallsRoute: typeof StallsRoute
  OrdersIdRoute: typeof OrdersIdRoute
  SupportIdRoute: typeof SupportIdRoute
  OrdersIndexRoute: typeof OrdersIndexRoute
  SupportIndexRoute: typeof SupportIndexRoute
  ApiPublicCashfreeCallbackRoute: typeof ApiPublicCashfreeCallbackRoute
  ApiPublicPayuCallbackRoute: typeof ApiPublicPayuCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories': {
      id: '/categories'
      path: '/categories'
      fullPath: '/categories'
      preLoaderRoute: typeof CategoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wallet': {
      id: '/wallet'
      path: '/wallet'
      fullPath: '/wallet'
      preLoaderRoute: typeof WalletRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/rider': {
      id: '/_authenticated/rider'
      path: '/rider'
      fullPath: '/rider'
      preLoaderRoute: typeof AuthenticatedRiderRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/vendor': {
      id: '/_authenticated/vendor'
      path: '/vendor'
      fullPath: '/vendor'
      preLoaderRoute: typeof AuthenticatedVendorRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/orders/': {
      id: '/orders/'
      path: '/orders'
      fullPath: '/orders/'
      preLoaderRoute: typeof OrdersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders/$id': {
      id: '/orders/$id'
      path: '/orders/$id'
      fullPath: '/orders/$id'
      preLoaderRoute: typeof OrdersIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stalls/': {
      id: '/stalls/'
      path: '/stalls'
      fullPath: '/stalls/'
      preLoaderRoute: typeof StallsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support/': {
      id: '/support/'
      path: '/support'
      fullPath: '/support/'
      preLoaderRoute: typeof SupportIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support/$id': {
      id: '/support/$id'
      path: '/support/$id'
      fullPath: '/support/$id'
      preLoaderRoute: typeof SupportIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cashfree/callback': {
      id: '/api/public/cashfree/callback'
      path: '/api/public/cashfree/callback'
      fullPath: '/api/public/cashfree/callback'
      preLoaderRoute: typeof ApiPublicCashfreeCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/payu/callback': {
      id: '/api/public/payu/callback'
      path: '/api/public/payu/callback'
      fullPath: '/api/public/payu/callback'
      preLoaderRoute: typeof ApiPublicPayuCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedRiderRoute: typeof AuthenticatedRiderRoute
  AuthenticatedVendorRoute: typeof AuthenticatedVendorRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedRiderRoute: AuthenticatedRiderRoute,
  AuthenticatedVendorRoute: AuthenticatedVendorRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AdminRoute: AdminRoute,
  AuthRoute: AuthRoute,
  CartRoute: CartRoute,
  CategoriesRoute: CategoriesRoute,
  NotificationsRoute: NotificationsRoute,
  ProfileRoute: ProfileRoute,
  TermsRoute: TermsRoute,
  WalletRoute: WalletRoute,
  StallsRoute: StallsRoute,
  OrdersIdRoute: OrdersIdRoute,
  SupportIdRoute: SupportIdRoute,
  OrdersIndexRoute: OrdersIndexRoute,
  SupportIndexRoute: SupportIndexRoute,
  ApiPublicCashfreeCallbackRoute: ApiPublicCashfreeCallbackRoute,
  ApiPublicPayuCallbackRoute: ApiPublicPayuCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
