/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as CartRouteImport } from './routes/cart'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as RiderRouteImport } from './routes/rider'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as VendorRouteImport } from './routes/vendor'
import { Route as OrdersIndexRouteImport } from './routes/orders.index'
import { Route as OrdersIdRouteImport } from './routes/orders.$id'
import { Route as ApiPublicPayuCallbackRouteImport } from './routes/api/public/payu/callback'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const RiderRoute = RiderRouteImport.update({
  id: '/rider',
  path: '/rider',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const VendorRoute = VendorRouteImport.update({
  id: '/vendor',
  path: '/vendor',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersIndexRoute = OrdersIndexRouteImport.update({
  id: '/orders/',
  path: '/orders/',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersIdRoute = OrdersIdRouteImport.update({
  id: '/orders/$id',
  path: '/orders/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPayuCallbackRoute = ApiPublicPayuCallbackRouteImport.update({
  id: '/api/public/payu/callback',
  path: '/api/public/payu/callback',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/cart': typeof CartRoute
  '/profile': typeof ProfileRoute
  '/rider': typeof RiderRoute
  '/terms': typeof TermsRoute
  '/vendor': typeof VendorRoute
  '/orders/$id': typeof OrdersIdRoute
  '/orders/': typeof OrdersIndexRoute
  '/api/public/payu/callback': typeof ApiPublicPayuCallbackRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/cart': typeof CartRoute
  '/profile': typeof ProfileRoute
  '/rider': typeof RiderRoute
  '/terms': typeof TermsRoute
  '/vendor': typeof VendorRoute
  '/orders/$id': typeof OrdersIdRoute
  '/orders': typeof OrdersIndexRoute
  '/api/public/payu/callback': typeof ApiPublicPayuCallbackRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/cart': typeof CartRoute
  '/profile': typeof ProfileRoute
  '/rider': typeof RiderRoute
  '/terms': typeof TermsRoute
  '/vendor': typeof VendorRoute
  '/orders/$id': typeof OrdersIdRoute
  '/orders/': typeof OrdersIndexRoute
  '/api/public/payu/callback': typeof ApiPublicPayuCallbackRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/cart'
    | '/profile'
    | '/rider'
    | '/terms'
    | '/vendor'
    | '/orders/$id'
    | '/orders/'
    | '/api/public/payu/callback'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/auth'
    | '/cart'
    | '/profile'
    | '/rider'
    | '/terms'
    | '/vendor'
    | '/orders/$id'
    | '/orders'
    | '/api/public/payu/callback'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/auth'
    | '/cart'
    | '/profile'
    | '/rider'
    | '/terms'
    | '/vendor'
    | '/orders/$id'
    | '/orders/'
    | '/api/public/payu/callback'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AuthRoute: typeof AuthRoute
  CartRoute: typeof CartRoute
  ProfileRoute: typeof ProfileRoute
  RiderRoute: typeof RiderRoute
  TermsRoute: typeof TermsRoute
  VendorRoute: typeof VendorRoute
  OrdersIdRoute: typeof OrdersIdRoute
  OrdersIndexRoute: typeof OrdersIndexRoute
  ApiPublicPayuCallbackRoute: typeof ApiPublicPayuCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rider': {
      id: '/rider'
      path: '/rider'
      fullPath: '/rider'
      preLoaderRoute: typeof RiderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vendor': {
      id: '/vendor'
      path: '/vendor'
      fullPath: '/vendor'
      preLoaderRoute: typeof VendorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders/': {
      id: '/orders/'
      path: '/orders'
      fullPath: '/orders/'
      preLoaderRoute: typeof OrdersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders/$id': {
      id: '/orders/$id'
      path: '/orders/$id'
      fullPath: '/orders/$id'
      preLoaderRoute: typeof OrdersIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/payu/callback': {
      id: '/api/public/payu/callback'
      path: '/api/public/payu/callback'
      fullPath: '/api/public/payu/callback'
      preLoaderRoute: typeof ApiPublicPayuCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AuthRoute: AuthRoute,
  CartRoute: CartRoute,
  ProfileRoute: ProfileRoute,
  RiderRoute: RiderRoute,
  TermsRoute: TermsRoute,
  VendorRoute: VendorRoute,
  OrdersIdRoute: OrdersIdRoute,
  OrdersIndexRoute: OrdersIndexRoute,
  ApiPublicPayuCallbackRoute: ApiPublicPayuCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
